apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: adguard-sync-secret
  namespace: family-reunion
spec:
  encryptedData:
    password: AgAuxsSUyr2BxiDwPdO1dmjLEIEC/ZZ582TWB8M19byp5CjtlMpblW+BKtF972sz5IL86jKW/Eu9i7wnqBfmRpcClNcuh/MtVVlN0ArDpadsoKESOjYvVPaSdbOogsXnYJFUdyTQv4JzNUeQNNECPTCun1F0cIALsRgefjIpbFlkOmFJL8iYfq4KVMF1jan1TQrwevmy/lzfy2t9K74V6hC/VevrBCo0i1Sb8tQa/tKbJu2SF04SAGVLyiQLFX3ECUTcFyqB1OAdMsmRSHMJ6gQUQL+776tp+7fj6X6VMObemn1R7Z84saX1NUsBAgYsgw/9YC5qDHU9aPODGKlL7K6zhQ8y1u6lFLHx1Rtbhp0dLtR1s29sXLCSOSGryiQPaQmAlrdDjVKf/1YWoRXLnz083jdxpcpHx44pMNlQ0m71MUZyQEBPInitREiHkLInFxgnbybCD/QjZt/0cD/VlYwDcQnCQx4IW/d7/XP6OXHd8pMi9bNJD9ZwHiHu4EwYo+jNU03p1OtCK50esRr6zfzmfK5E4u0r7aVKxPY4IHv/WuJB9M/6zDPLoEB3UOY0bYEOW7EJXowi25gLf3hkZG9d4LhkCpMlD9IUFMFRV/7INFZEtkiLGVH0Mg4NoLZp2JV52M3SVtOrxUNjr0L7wTZYrUgjeMdPgOh3UaarnCgMZuxqvvN4x+jIUgnYX7ri+QUw0M70Xnb/Eq3MH3J3
    username: AgAxZSl1V8Lo7vTLAxhNMeRwvyVeah60hny6NkjhIpNTDD32ie1+HzedOea21lfC5YGJfjKnz3rsTdSuWySZNUl0AdWyOK+z7YwYOrMIpfCrQ+wacwTEoDnYdW234zIanCi8Xl0qLVBJSfmQBYYJ/qhGp9Ul8ItAX3T3D/UznwzJUf2z+xY/jacL5ZiBYOMXWmXZLhqmNxV8lSUZOSogOBN1runA33CD4FjsAOr2Tba/8U48fl6W9gpzecGJSqFx4BHGqXrYe0PEt7i798hOYEJOdSv7cYlhluuboyvNeokJVGbTNqQMRhdJonnand1eiVTgyiQDecsRqQqVd67pwqfrQTC4Qu0T74sFSXoKmWR4FvQ9h507L/9Gr2aHtAlponlIDzDfzQ6fwUfRafkWeXX1eKWNQiA2YTDL+QdQWeBHDKbI4G6s2yLXMk4jv5Tsu30kornQaQUrSqFUW/KAlDi2ryFnxC/VR+DHNJSy7NpIllHk3aP/B+L4aespO1Eawp59B/oprscOH53QYFLVZDX7xs37qci5z51RS4sdbylYkDqkVcyHxWJw7DA4PgNdAeQXWPQqV37l+PbHyYWirgiKfBBlDba2nJnnGw56wcAfi+WYkQd0mbcOUZiLNq+C1dkeG6GLtrJ2JbfhnHJ+sj+aIJ4//V7c5+PSRbc/RnMlbKUpQzzMfODGWTHd3S4AhwYXOQ36gA==
  template:
    metadata:
      name: adguard-sync-secret
      namespace: family-reunion
    type: Opaque
