apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: family-reunion
type: Opaque
stringData:
  POSTGRES_DB: reuniondb
  POSTGRES_USER: reunion
  POSTGRES_PASSWORD: AllAboutMe3971!!
